export const projects = [
  {
    title: 'Hoop Books Pre-Accounting',
    description: "Using React, Node.js, Express & firebase you'll use for pre acconting program. The App is called Hoop Books and it is a simple accounting app that allows users to calculate their finance easly.",
      image: '/images/1.png',
      tags: ['Firebase', 'Express',,'JavaScript', 'React', 'Node'],
    source: 'https://github.com/akayee/hoopbooks',
    visit: 'https://hoop-books.firebaseapp.com/',
    id: 0,
  },
  {
    title: 'GoldNederland E-Commerce',
    description:"Using React, redux and firebase you'll see in this project.And this program has cool theme.",
    image: '/images/2.png',
    tags: ['React', 'JavaScript', 'Redux', 'Firebase'],
    source: 'https://github.com/akayee/goldnederland',
    visit: 'https://goldnederland-91ebc.web.app/',
    id: 1,
  },
  {
    title: 'Erasmus Education Website - Compass Education',
    description: "This is Erasmus Education website. Erasmus students makes their request and take more information about erasmus in this site.",
      image: '/images/3.jpg',
      tags: ['React','JavaScript', 'Firebase'],
    source: 'https://github.com/akayee/compass',
    visit: 'https://compass-bbe06.firebaseapp.com/home',
    id: 2,
  },
  {
    title: 'Strategy and Activity Report Program ',
    description: "This program allows user to create Strategy and Activity report easly. And also user can create reports daily,monthly , by location ext.",
    image: '/images/4.jpg',
    tags: ['React' ,'Redux','.Net Core','Private Project'],
    source: '',
    visit: '',
    id: 3,
  },
  {
    title: 'Solar System Website',
    description: "This website contains solar system and projects informations whic is working on Turkey already.",
    image: '/images/5.png',
    tags: ['React','JavaScript', 'Firebase'],
    source: 'https://github.com/akayee/adenerji',
    visit: 'https://adenerjimuhendislik.com/',
    id: 4,
  },
  {
    title: 'Bakery Mobile Application',
    description: "This app using for bakery order management. And E-commerce for bakery.",
    image: '/images/camaltilogo.png',
    tags: ['React Native', 'Redux','JavaScript', 'Firebase'],
    source: 'https://github.com/akayee/camaltiCalisan',
    visit: '',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2013, text: 'Started my journey', },
  { year: 2014, text: 'Worked for Local Goverment. Software Developer Role', },
  { year: 2015, text: 'Worked Ericsson for Release Manager Role', },
  { year: 2016, text: 'Promoted to Test Team Lead', },
  { year: 2017, text: 'Founded my own company', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Worked Local Goverment for SOftware Developer', },
  { year: 2020, text: 'Deployed my strategy report program', },
  { year: 2021, text: 'Still improving my Strategy program', },
];